services:
  - type: worker
    name: tg-fitness-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python -m app.bot
    envVars:
      - key: TZ
        value: Europe/Moscow
      - key: PYTHON_VERSION
        value: 3.11.9
  - type: web
    name: tg-fitness-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: TZ
        value: Europe/Moscow
      - key: PYTHON_VERSION
        value: 3.11.9
